In [1]:
import pandas as pd
import numpy as np

In [2]:
sector_df = pd.read_csv('../data/industry_mappings.csv')
data = pd.read_csv('../data/data_with_open_prices.csv')

In [3]:
sector_df

         symbol                company_name                      sector
0    ABAN.N0000       ABANS ELECTRICALS PLC      Electronics/Appliances
1    AFSL.N0000           ABANS FINANCE PLC      Finance/Rental/Leasing
2     AEL.N0000      ACCESS ENGINEERING PLC  Engineering & Construction
3     ACL.N0000              ACL CABLES PLC         Electrical Products
4    APLA.N0000            ACL PLASTICS PLC      Industrial Specialties
..          ...                         ...                         ...
295  VFIN.N0000        VALLIBEL FINANCE PLC      Finance/Rental/Leasing
296   VLL.N0000              VIDULLANKA PLC          Electric Utilities
297   VLL.X0000              VIDULLANKA PLC          Electric Utilities
298  VONE.N0000            VALLIBEL ONE PLC      Wholesale Distributors
299  VPEL.N0000  VALLIBEL POWER ERATHNA PLC          Electric Utilities

[300 rows x 3 columns]

In [4]:
symbols = np.array(sector_df['symbol'].str.split('.').tolist())[:,0]
suffixes = np.array(sector_df['symbol'].str.split('.').tolist())[:,1]

sector_df['symbol'] = symbols
sector_df['suffix'] = suffixes

In [5]:
sector_df

    symbol                company_name                      sector suffix
0     ABAN       ABANS ELECTRICALS PLC      Electronics/Appliances  N0000
1     AFSL           ABANS FINANCE PLC      Finance/Rental/Leasing  N0000
2      AEL      ACCESS ENGINEERING PLC  Engineering & Construction  N0000
3      ACL              ACL CABLES PLC         Electrical Products  N0000
4     APLA            ACL PLASTICS PLC      Industrial Specialties  N0000
..     ...                         ...                         ...    ...
295   VFIN        VALLIBEL FINANCE PLC      Finance/Rental/Leasing  N0000
296    VLL              VIDULLANKA PLC          Electric Utilities  N0000
297    VLL              VIDULLANKA PLC          Electric Utilities  X0000
298   VONE            VALLIBEL ONE PLC      Wholesale Distributors  N0000
299   VPEL  VALLIBEL POWER ERATHNA PLC          Electric Utilities  N0000

[300 rows x 4 columns]

In [6]:
unique_symbols = sector_df['symbol'].unique().tolist()
sector_map = { symbol : sector_df[sector_df['symbol'] == symbol]['sector'].values[0]  for symbol in symbols}

In [7]:
symbols = np.array(data['symbol'].str.split('.').tolist())[:,0]
suffixes = np.array(data['symbol'].str.split('.').tolist())[:,1]

data['symbol'] = symbols
data['suffix'] = suffixes

In [8]:
data['sector'] = data['symbol']
data['sector'] = data['sector'].map(sector_map)
data['symbol'].nunique()

268

In [ ]:
data.to_csv('../output/01_sector-data-imputed.csv',index = False)